// Demo catalogue. Every product is fictional. Replace with your real range via `npm run seed` or your own import.
//
// facts:  the "Access Facts" panel. Keep labels consistent across products so people can compare.
// easy:   1-2 sentence plain-language summary (aim for a reading age of about 9-11).

const F = (hands, effort, weight, setup, extra = []) => [
  ['Hands needed', hands],
  ['Effort to use', effort],
  ['Weight', weight],
  ['Setup', setup],
  ...extra,
];

export const PRODUCTS = [
  {
    slug: 'rocker-knife', name: 'Rocker Knife', category: 'kitchen', glyph: 'knife', tone: 'persimmon', price: 2900, stock: 40, featured: 1,
    tagline: 'Cut with a rocking push, using one hand.',
    easy: 'Rest your palm on the handle and rock the blade. It cuts food without you needing to grip tightly or use a fork.',
    description: 'A curved stainless-steel blade with a thick, upright palm handle. You cut by rocking, so the force comes from your arm and body instead of a pinching grip. Works for bread, vegetables and soft meat. Dishwasher safe.',
    needs: ['dexterity', 'mobility'], traits: ['one-hand', 'low-grip', 'no-setup'],
    facts: F('One hand', 'Light rocking push', '190 g', 'None', [['Blade', 'Rounded tip, 18 cm'], ['Cleaning', 'Dishwasher safe']]),
  },
  {
    slug: 'palm-press-jar-opener', name: 'Palm-Press Jar Opener', category: 'kitchen', glyph: 'jar', tone: 'sun', price: 2400, stock: 55, featured: 1,
    tagline: 'Press down with your palm. The lid does the rest.',
    easy: 'Put it on the lid and push down with your flat hand. The rubber teeth turn the lid for you.',
    description: 'A wide rubber-toothed cone that grips lids from 25 mm to 90 mm. Press down with the flat of your hand and twist gently, or hold the cone still and turn the jar. No pinching, no squeezing.',
    needs: ['dexterity'], traits: ['one-hand', 'low-grip', 'lightweight', 'no-setup'],
    facts: F('One hand', 'Light downward press', '140 g', 'None', [['Fits lids', '25 mm to 90 mm']]),
  },
  {
    slug: 'talking-kitchen-scale', name: 'Talking Kitchen Scale', category: 'kitchen', glyph: 'scale', tone: 'sky', price: 5800, stock: 18, featured: 1,
    tagline: 'Says the weight out loud. Big buttons you can feel.',
    easy: 'Put food on the scale and it tells you the weight in a clear voice. The buttons are big and have raised marks.',
    description: 'Weighs up to 5 kg to the nearest gram. Speaks each reading in a clear voice at adjustable volume, and shows it in 5 cm-tall high-contrast digits. Three raised-dot buttons: on, zero, and units. Plug-in or 4 AAA batteries.',
    needs: ['vision'], traits: ['audio', 'tactile', 'big-print'],
    facts: F('One hand', 'Light button press', '780 g', 'Insert batteries (2 min)', [['Sight needed', 'None. Speaks every reading'], ['Volume', 'Adjustable, 3 levels'], ['Display', 'Digits 5 cm tall']]),
  },
  {
    slug: 'tilt-pour-kettle-stand', name: 'Tilt-Pour Kettle Stand', category: 'kitchen', glyph: 'kettle', tone: 'rose', price: 4600, stock: 22, featured: 0,
    tagline: 'Pour hot water without lifting the kettle.',
    easy: 'The kettle sits in a frame. You tip it with a light push and hot water comes out slowly, so you do not have to lift it.',
    description: 'A weighted frame holds most standard kettles and tips them forward on a smooth hinge with a light push of the wrist. A drip tray and a raised side guard keep spills away from hands. Not suitable for kettles over 2 litres.',
    needs: ['mobility', 'dexterity'], traits: ['one-hand', 'low-grip'],
    facts: F('One hand', 'Light push with the wrist', '1.6 kg', 'Place kettle in frame (1 min)', [['Kettle size', 'Up to 2 litres']]),
  },
  {
    slug: 'weighted-utensil-set', name: 'Weighted Utensil Set', category: 'kitchen', glyph: 'spoon', tone: 'sage', price: 3200, stock: 30, featured: 0,
    tagline: 'Fork, spoon and knife with steady weight for hand tremor.',
    easy: 'The extra weight in the handles helps keep your hand steady, and the fat handles are easy to hold.',
    description: 'Three utensils with 200 g weighted handles and soft, wide, angled grips. The weight damps small shakes so food stays on the spoon. Bendable necks let you set the angle that suits you.',
    needs: ['dexterity'], traits: ['low-grip', 'no-setup'],
    facts: F('Either hand', 'Light hold; wide soft grip', '200 g each', 'Bend neck to your angle (1 min)', [['Cleaning', 'Dishwasher safe']]),
  },
  {
    slug: 'button-hook-zip-pull', name: 'Button Hook and Zip Pull', category: 'dressing', glyph: 'hook', tone: 'persimmon', price: 1400, stock: 80, featured: 1,
    tagline: 'Do up buttons and zips with one hand.',
    easy: 'Slide the wire loop through the button hole, hook the button and pull. The big ring handle is easy to hold.',
    description: 'A wire loop on a chunky cushioned handle threads buttons through holes, and a ring clip on the end grabs small zip pulls. Left- and right-handed friendly.',
    needs: ['dexterity', 'mobility'], traits: ['one-hand', 'lightweight', 'no-setup'],
    facts: F('One hand', 'Light pull', '45 g', 'None'),
  },
  {
    slug: 'sock-slider', name: 'Sock Slider', category: 'dressing', glyph: 'sock', tone: 'sky', price: 1900, stock: 45, featured: 0,
    tagline: 'Put on socks without bending down.',
    easy: 'Slide the sock over the frame, drop it on the floor, put your foot in and pull the straps up.',
    description: 'A flexible half-tube with two long soft-loop straps. Load a sock, lower it to the floor, slip your foot in and pull. The straps are 75 cm long so no bending or reaching is needed.',
    needs: ['mobility', 'dexterity'], traits: ['one-hand', 'lightweight', 'no-setup'],
    facts: F('One or two hands', 'Light pull', '120 g', 'None', [['Strap length', '75 cm']]),
  },
  {
    slug: 'elastic-no-tie-laces', name: 'Elastic No-Tie Laces (6 pairs)', category: 'dressing', glyph: 'laces', tone: 'sun', price: 1200, stock: 120, featured: 0,
    tagline: 'Slip-on shoes that look like lace-ups.',
    easy: 'Thread these once. After that your shoes slip on and off with no tying, ever.',
    description: 'Stretchy round laces with a small locking toggle. Thread them once, lock, and shoes slip on and off. Six pairs in mixed colours so you can tell them apart by sight, and one pair in black.',
    needs: ['dexterity', 'cognitive'], traits: ['one-hand', 'low-grip'],
    facts: F('One hand', 'Light pull', '40 g per pair', 'Thread once (5 min, helper useful)', [['Length', '80 cm each']]),
  },
  {
    slug: 'reach-grabber', name: 'Reach Grabber, 80 cm', category: 'mobility', glyph: 'grabber', tone: 'sage', price: 2700, stock: 34, featured: 1,
    tagline: 'Pick things up from floor or shelf, standing or seated.',
    easy: 'Squeeze the trigger and the jaws close. It picks up things from the floor or a high shelf.',
    description: 'A lightweight aluminium pole with a pistol-grip trigger and rubbery jaws that hold anything from a coin to a tin can. A magnetic tip picks up keys. Folds in the middle for a bag or wheelchair pocket.',
    needs: ['mobility', 'dexterity'], traits: ['one-hand', 'lightweight'],
    facts: F('One hand', 'Light trigger squeeze', '260 g', 'None', [['Length', '80 cm (folds to 42 cm)'], ['Lifts', 'Up to 1 kg']]),
  },
  {
    slug: 'folding-cane', name: 'Folding Cane, Cushion Grip', category: 'mobility', glyph: 'cane', tone: 'sun', price: 5400, stock: 25, featured: 0,
    tagline: 'A cane that folds small and is kind to sore hands.',
    easy: 'A light cane with a soft, wide handle. It folds into four parts to fit in a bag.',
    description: 'A light aluminium cane, adjustable from 79 cm to 94 cm, with a wide contoured foam handle that spreads pressure across your palm. Folds into four sections with an elastic cord. Supports up to 125 kg. This is a general-use cane, not a medical device: ask your clinician if you are unsure what suits you.',
    needs: ['mobility', 'dexterity'], traits: ['lightweight', 'low-grip'],
    facts: F('One hand', 'Light hold; wide handle', '350 g', 'Set height with the push-button (2 min)', [['Height', '79 cm to 94 cm'], ['Supports', 'Up to 125 kg']]),
  },
  {
    slug: 'shower-stool', name: 'Shower Stool with Backrest', category: 'bathroom', glyph: 'stool', tone: 'sky', price: 8900, stock: 12, featured: 0,
    tagline: 'A steady seat for showering, with a back to lean on.',
    easy: 'A seat with a back and non-slip feet, so you can sit down in the shower.',
    description: 'A tool-free stool with a moulded seat that drains, a supportive backrest and rubber feet. Legs adjust from 38 cm to 52 cm. Supports up to 136 kg. Choose the height that lets your feet sit flat on the floor.',
    needs: ['mobility'], traits: ['no-setup'],
    facts: F('Not applicable', 'None', '3.6 kg', 'Snap legs in (5 min, no tools)', [['Seat height', '38 cm to 52 cm'], ['Supports', 'Up to 136 kg']]),
  },
  {
    slug: 'angled-bath-sponge', name: 'Long Angled Bath Sponge', category: 'bathroom', glyph: 'sponge', tone: 'rose', price: 1600, stock: 60, featured: 0,
    tagline: 'Wash your back and feet without stretching.',
    easy: 'A sponge on a long bendy handle so you can reach your back and feet.',
    description: 'A 42 cm curved handle with a soft rubber grip and a replaceable sponge head. The curve reaches the middle of the back and the feet without twisting or bending forward.',
    needs: ['mobility', 'dexterity'], traits: ['one-hand', 'lightweight', 'no-setup'],
    facts: F('One hand', 'Light hold', '95 g', 'None', [['Length', '42 cm']]),
  },
  {
    slug: 'talking-pill-organizer', name: 'Talking Pill Organizer', category: 'memory', glyph: 'pills', tone: 'sage', price: 4200, stock: 20, featured: 1,
    tagline: 'Lights up, says it is time, and shows what to take.',
    easy: 'When it is time for a dose, the right box lights up and a voice tells you. Boxes open with a light push.',
    description: 'Seven days by four times a day. At each set time the correct compartment lights and a voice reminder plays. Lids open with a push button, not a fingernail. Set times by voice menu or the big buttons. Not a medical device: it cannot check that you took the right medicine.',
    needs: ['cognitive', 'vision', 'dexterity'], traits: ['audio', 'flash', 'tactile', 'low-grip'],
    facts: F('One hand', 'Light button push', '410 g', 'Set the times (10 min, helper useful)', [['Reminders', 'Voice and light'], ['Battery', '3 AA, about 6 months']]),
  },
  {
    slug: 'flashing-doorbell', name: 'Flashing Doorbell Receiver', category: 'hearing', glyph: 'bell', tone: 'rose', price: 4900, stock: 27, featured: 1,
    tagline: 'A doorbell you see, plus a vibrating pager for your pocket.',
    easy: 'When someone rings the bell, a bright light flashes and a small pager buzzes.',
    description: 'A wireless push button for the door and two receivers: a plug-in lamp that flashes very brightly, and a clip-on vibrating pager. Pick from eight flash speeds and a soft or loud chime. Range 100 m in open air.',
    needs: ['hearing'], traits: ['flash', 'vibrate', 'no-setup'],
    facts: F('Not applicable', 'None', '160 g receiver', 'Pair with the button (5 min)', [['Alert', 'Light and vibration'], ['Range', 'About 100 m open air']]),
  },
  {
    slug: 'bed-shaker-alarm-clock', name: 'Bed-Shaker Alarm Clock', category: 'hearing', glyph: 'clock', tone: 'sun', price: 3800, stock: 33, featured: 0,
    tagline: 'Wakes you with a strong shake under the pillow.',
    easy: 'A pad goes under your pillow or mattress and shakes when the alarm goes off. There is a bright light too.',
    description: 'A clock with big 4 cm digits and a slim vibrating pad that fits under a pillow or mattress. You can add a loud tone and a strobe light, or use vibration alone. Battery backup keeps your alarm during a power cut.',
    needs: ['hearing'], traits: ['vibrate', 'flash', 'big-print'],
    facts: F('One hand', 'Light button press', '520 g', 'Plug in and set the time (5 min)', [['Alert', 'Vibration, light, optional sound'], ['Display', 'Digits 4 cm tall']]),
  },
  {
    slug: 'tv-listening-speaker', name: 'TV Listening Speaker', category: 'hearing', glyph: 'speaker', tone: 'sky', price: 7900, stock: 14, featured: 0,
    tagline: 'A small speaker that sits next to you and makes speech clearer.',
    easy: 'It sits next to your chair and makes voices on the TV easier to hear, without turning the TV up.',
    description: 'A speaker with a 6 m lead that plugs into the TV. A dedicated “voice boost” switch lifts speech over background music. Big rotary volume and voice-boost dials with raised marks. Not a hearing aid.',
    needs: ['hearing'], traits: ['tactile', 'big-print'],
    facts: F('One hand', 'Light dial turn', '1.1 kg', 'Plug into TV (5 min)', [['Lead', '6 m'], ['Controls', 'Two large dials']]),
  },
  {
    slug: 'tactile-talking-watch', name: 'Tactile Talking Watch', category: 'vision', glyph: 'watch', tone: 'sun', price: 8800, stock: 16, featured: 1,
    tagline: 'Read the time by touch or by voice.',
    easy: 'Flip the cover to feel the hands, or press a button and the watch says the time out loud.',
    description: 'A hinged glass cover opens so you can feel the raised hour marks and slender hands. One press speaks the time and date. A strap that fits wrists from 14 cm to 21 cm. Water-resistant to splashes; not for swimming.',
    needs: ['vision'], traits: ['tactile', 'audio', 'big-print'],
    facts: F('One hand', 'Light button press', '62 g', 'Set the time (10 min, helper useful)', [['Sight needed', 'None. Feel it or hear it'], ['Battery', 'Replaceable, about 2 years']]),
  },
  {
    slug: 'led-handheld-magnifier', name: 'LED Handheld Magnifier', category: 'vision', glyph: 'magnifier', tone: 'persimmon', price: 3500, stock: 48, featured: 0,
    tagline: 'Bright, clear 5x magnifier with a big soft handle.',
    easy: 'Hold it over small print. It makes the words five times bigger and lights them up.',
    description: '5x magnification with 12 lights, a warm and a white setting. A 9 cm lens on a wide cushioned handle that suits a weak grip. Comes with a cord so it can hang round your neck.',
    needs: ['vision', 'dexterity'], traits: ['lightweight', 'low-grip', 'big-print'],
    facts: F('One hand', 'Light hold', '220 g', 'Insert batteries (2 min)', [['Magnification', '5x'], ['Lens', '9 cm']]),
  },
  {
    slug: 'bump-dots-labelling-kit', name: 'Bump Dots Labelling Kit', category: 'vision', glyph: 'dots', tone: 'sky', price: 1100, stock: 150, featured: 0,
    tagline: 'Mark the buttons that matter so you can find them by touch.',
    easy: 'Stick a raised dot on the start button of your oven or microwave. Now you can find it by feel.',
    description: '120 raised adhesive dots in three sizes and six colours, plus a set of 40 large-print labels. Use them on microwave and oven controls, remote controls, light switches and washing machines.',
    needs: ['vision'], traits: ['tactile', 'big-print', 'no-setup'],
    facts: F('One hand', 'Peel and press', '30 g', 'Stick on (1 min per dot)', [['In the box', '120 dots, 40 labels']]),
  },
  {
    slug: 'bold-line-notebook', name: 'Bold-Line Notebook', category: 'vision', glyph: 'notebook', tone: 'sun', price: 900, stock: 90, featured: 0,
    tagline: 'Thick black lines on cream paper. Easier to write on, easier to read.',
    easy: 'The lines are thick and black, so it is easier to see where to write.',
    description: 'A5 spiral notebook with 100 pages, 10 mm bold black lines on non-glare cream paper. Thick paper stops ink showing through. Lies flat when open.',
    needs: ['vision'], traits: ['big-print', 'lightweight', 'no-setup'],
    facts: F('Either hand', 'None', '310 g', 'None', [['Lines', '10 mm bold black'], ['Pages', '100']]),
  },
  {
    slug: 'picture-symbol-board', name: 'Picture-Symbol Communication Board', category: 'comms', glyph: 'board', tone: 'sage', price: 2200, stock: 38, featured: 0,
    tagline: 'Point to pictures to say what you need.',
    easy: 'A board with lots of pictures. Point to the picture to tell people what you want, feel or need.',
    description: 'A wipe-clean, A4 laminated board with 84 common symbols across everyday needs (food, pain, toilet, feelings, places) and a yes/no row. Carry-clip, and a wipe-clean pen to add your own words.',
    needs: ['speech', 'cognitive'], traits: ['pictures', 'big-print', 'lightweight', 'no-setup'],
    facts: F('One finger to point', 'None', '180 g', 'None', [['Symbols', '84 plus a blank area']]),
  },
  {
    slug: 'voice-output-button', name: 'Recordable Voice Button', category: 'comms', glyph: 'button', tone: 'persimmon', price: 3400, stock: 42, featured: 1,
    tagline: 'Record any message. Press the big button to play it.',
    easy: 'Say something into it once. When you press the big button, it says it again.',
    description: 'A 7.5 cm button that plays back a recorded message of up to 20 seconds. Volume dial with raised marks. Sturdy enough to hit with a palm, elbow or head. Use one button for “I need help” or “Yes, please”, or set out several.',
    needs: ['speech', 'cognitive', 'dexterity'], traits: ['audio', 'low-grip', 'tactile'],
    facts: F('One hand, any part of the body', 'Very light press', '150 g', 'Record a message (2 min)', [['Message', 'Up to 20 seconds'], ['Battery', '3 AAA']]),
  },
  {
    slug: 'visual-routine-timer', name: 'Visual Routine Timer', category: 'memory', glyph: 'timer', tone: 'sage', price: 3100, stock: 36, featured: 1,
    tagline: 'See time running out. No ticking, no sudden alarm.',
    easy: 'A coloured disc gets smaller as time goes by. When it ends, a soft light glows. It does not make a loud noise.',
    description: 'A red disc shrinks as time passes, so you can see how long is left without reading a clock. Choose from 5 to 60 minutes. It ends with a gentle glow and optional soft chime. Silent while it runs.',
    needs: ['cognitive', 'sensory'], traits: ['calm', 'flash', 'pictures', 'no-setup'],
    facts: F('One hand', 'Light dial turn', '210 g', 'None', [['Sound while running', 'None'], ['Ends with', 'Soft glow, optional chime']]),
  },
  {
    slug: 'weighted-lap-pad', name: 'Weighted Lap Pad, 2 kg', category: 'calm', glyph: 'pad', tone: 'rose', price: 4500, stock: 21, featured: 0,
    tagline: 'A heavy, soft pad for a calming, steady feeling on the lap.',
    easy: 'A soft, heavy pad. Some people find it calming to rest on their lap.',
    description: 'A 2 kg pad, 60 x 40 cm, filled with glass beads in stitched channels so the weight stays spread out. Plush cover, removable, machine washable. Not recommended for anyone who cannot remove it themselves without checking with a clinician.',
    needs: ['sensory', 'cognitive'], traits: ['calm', 'no-setup'],
    facts: F('None', 'None', '2 kg', 'None', [['Size', '60 x 40 cm'], ['Cleaning', 'Cover machine washable']]),
  },
  {
    slug: 'soft-noise-earmuffs', name: 'Soft Noise-Reducing Earmuffs', category: 'calm', glyph: 'earmuffs', tone: 'sky', price: 2700, stock: 47, featured: 0,
    tagline: 'Turns loud places down to a comfortable level.',
    easy: 'They make loud places quieter. You can still hear people talking to you.',
    description: 'Padded earmuffs that reduce noise by 22 dB with a soft, seam-free inside. Adjustable headband, no wires or batteries. Comes in a small bag for the trip to the shops, the cinema or the dentist.',
    needs: ['sensory', 'hearing'], traits: ['calm', 'lightweight', 'no-setup'],
    facts: F('None', 'None', '210 g', 'Set the headband (1 min)', [['Noise reduction', '22 dB']]),
  },
  {
    slug: 'voice-control-smart-plugs', name: 'Voice-Control Smart Plugs (4)', category: 'tech', glyph: 'plug', tone: 'sun', price: 3600, stock: 65, featured: 0,
    tagline: 'Turn lamps and fans on and off by voice or phone.',
    easy: 'Plug your lamp into these. Then say “lamp on” or use your phone to turn it on.',
    description: 'Four Wi-Fi plugs that work with the main voice assistants and a phone app with big controls. Also has a big on/off button on the plug itself for when the internet is down. Needs a 2.4 GHz Wi-Fi network.',
    needs: ['mobility', 'vision', 'dexterity'], traits: ['voice', 'no-setup'],
    facts: F('None once set up', 'Voice or light button press', '80 g each', 'Connect to Wi-Fi (15 min, helper useful)', [['Works with', 'Voice assistants and app']]),
  },
  {
    slug: 'lever-door-adapter', name: 'Lever Door-Knob Adapter (2)', category: 'home', glyph: 'lever', tone: 'persimmon', price: 1800, stock: 70, featured: 0,
    tagline: 'Turns a round knob into a lever you can push with your elbow.',
    easy: 'Slip it over a round door knob. Now you can open the door with a push down, not a twist.',
    description: 'Two rubber-lined levers that fit round knobs from 45 mm to 65 mm without tools. Open the door by pushing down with a palm, wrist or elbow. Not suited to deadbolts.',
    needs: ['dexterity', 'mobility'], traits: ['one-hand', 'low-grip', 'no-setup'],
    facts: F('One hand, wrist or elbow', 'Light downward push', '110 g each', 'Slip on (1 min, no tools)', [['Fits knobs', '45 mm to 65 mm']]),
  },
  {
    slug: 'hands-free-book-stand', name: 'Hands-Free Book and Tablet Stand', category: 'home', glyph: 'stand', tone: 'sage', price: 3900, stock: 29, featured: 0,
    tagline: 'Holds a book or tablet at any angle, no holding needed.',
    easy: 'It holds your book or tablet up for you, so you do not need to hold it. Set it at any angle.',
    description: 'A stable stand with a flexible arm and clamp that holds books, tablets and phones from 9 to 32 cm wide. Clips onto a bed frame, chair arm or table. Page-holder bars keep pages open with one hand.',
    needs: ['mobility', 'dexterity'], traits: ['one-hand', 'low-grip'],
    facts: F('None once set', 'Light adjust', '1.2 kg', 'Clamp to a table or bed (3 min)', [['Holds', 'Books and screens 9 to 32 cm wide']]),
  },
  {
    slug: 'big-button-phone', name: 'Big-Button Photo Phone', category: 'tech', glyph: 'phone', tone: 'rose', price: 6400, stock: 17, featured: 1,
    tagline: 'Press a photo to call someone. Loud, clear and simple.',
    easy: 'Nine big photo buttons. Press a photo to call that person. Rings loud and flashes.',
    description: 'A landline-style phone with nine photo-memory buttons, large 2 cm number keys, a loud ringer with strobe and a hearing-aid compatible earpiece with extra volume. Speaks each number as you dial it.',
    needs: ['vision', 'cognitive', 'hearing', 'dexterity'], traits: ['big-print', 'flash', 'audio', 'pictures', 'low-grip'],
    facts: F('One hand', 'Light button press', '900 g', 'Plug in and add photos (15 min, helper useful)', [['Keys', 'Large, 2 cm'], ['Ringer', 'Loud, with flashing light']]),
  },
];
